version: "3.5"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - starter_net
  temporal:
    image: temporalio/auto-setup:0.28.0
    ports:
     - "7233:7233"
    environment:
      - "AUTO_SETUP=true"
      - "DB=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PWD=root"
      - "MYSQL_SEEDS=mysql"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    networks:
      - starter_net
    depends_on:
      - mysql
  temporal-admin-tools:
    image: temporalio/admin-tools:0.28.0
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    networks:
      - starter_net
    depends_on:
      - temporal
  temporal-web:
    image: temporalio/web:0.28.1
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    networks:
      - starter_net
    ports:
      - "8088:8088"
    depends_on:
      - temporal
networks:
  starter_net:
    name: starter_network

