version: "3.5"
services:
  # worker
  worker:
    image: jasonsoft/starter:latest
    depends_on:
      - event
      - wallet
    volumes:
      - "./configs/app.yml:/starter/configs/app.yml"
    command: /starter/starter worker
    networks:
      - starter_net

  # wallet
  wallet:
    image: jasonsoft/starter:latest
    volumes:
      - "./configs/app.yml:/starter/configs/app.yml"
    command: /starter/starter wallet
    networks:
      - starter_net
      
  # event
  event:
    image: jasonsoft/starter:latest
    volumes:
      - "./configs/app.yml:/starter/configs/app.yml"
    command: /starter/starter event
    networks:
      - starter_net

  # bff
  bff:
    image: jasonsoft/starter:latest
    depends_on:
        - event
        - wallet
    # ports:
    #   - "10080:10080"
    volumes:
      - "./configs/app.yml:/starter/configs/app.yml"
    command: /starter/starter bff
    networks:
      - starter_net

networks:
  starter_net:
    external:
      name: starter_network 

      
  # event-dapr:
  #   image: "daprio/daprd:0.10.0"
  #   command: [
  #     "./daprd",
  #     "-app-id", "event",
  #     "-app-port", "10010",
  #     "-placement-host-address", "placement:50006" # Dapr's placement service can be reach via the docker DNS entry
  #     ]
  #   volumes:
  #       - "./components/:/components" # Mount our components folder for the runtime to use
  #   depends_on:
  #     - event
  #   network_mode: "service:event" # Attach the event-dapr service to the event network namespace
