env: local
mode: debug
databases:
  - name: starter
    address: mysql:3306
    username: root
    password: root
    dbname: starter_db
redis:
  cluster_mode: false
  addresses:
    - "redis:6379"
  password:
  max_retries: 1
  pool_size_per_node: 2
  db: 1
temporal:
  address: "temporal:7233"
jaeger:
  advertise_addr: http://jaeger-all-in-one:14268/api/traces
logs:
  - name: clog
    type: console
    min_level: debug
bff:
  http_bind: ":10080"
  http_advertise_addr: "bff:10080"
event:
  grpc_bind: ":10010"
  grpc_advertise_addr: "event:10010"
wallet:
  grpc_bind: ":10020"
  grpc_advertise_addr: "wallet:10020"